# Generated by Django 4.1.7 on 2023-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='collection',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='instruction',
            name='taskId',
            field=models.TextField(default='QSDF65434'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruction',
            name='api_key',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='completedAt',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='createdAt',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instru',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='typeInstru',
            field=models.TextField(default='Instru'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='urgency',
            field=models.TextField(default='now'),
        ),
    ]
