# Generated by Django 4.1.7 on 2023-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='api_key',
            field=models.TextField(default='DSQSF453'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='urgency',
            field=models.TextField(default='now'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='typeInstru',
            field=models.TextField(default='Instru'),
        ),
    ]
