# Generated by Django 4.1.7 on 2023-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0002_instruction_api_key_instruction_urgency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='collection',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
