# Generated by Django 4.1.7 on 2023-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0004_alter_instruction_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='id',
        ),
        migrations.AddField(
            model_name='instruction',
            name='askId',
            field=models.TextField(default='kjhgfdggh', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruction',
            name='api_key',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='completedAt',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='createdAt',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instru',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.TextField(default=' '),
        ),
    ]
