# Generated by Django 4.1.7 on 2023-03-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0005_remove_instruction_id_instruction_askid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='askId',
            new_name='taskId',
        ),
    ]
