# Generated by Django 4.1.7 on 2023-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datano', '0007_instruction_id_alter_instruction_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='taskId',
            field=models.TextField(),
        ),
    ]
